project_id = "ksbnwfeoojalrhrxvcaf"

[functions.navigation-ai-chat]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.broadcast-notification]
verify_jwt = false
